#ifndef USART_CONFIG_H
#define USART_CONFIG_H

/*
Possible options for USART_Baud:
1-USART_STD_BAUD_1200		2-USART_STD_BAUD_2400		3-USART_STD_BAUD_9600
4-USART_STD_BAUD_19200		5-USART_STD_BAUD_38400		6-USART_STD_BAUD_57600
7-USART_STD_BAUD_115200		8-USART_STD_BAUD_230400		9-USART_STD_BAUD_460800
10-USART_STD_BAUD_921600	11-USART_STD_BAUD_2M		12-USART_STD_BAUD_3M
 */
#define USART_BAUD		USART_STD_BAUD_9600
/*
 Possible options for USART_Mode:
 1-USART_MODE_TXRX		2-USART_MODE_ONLY_TX		3-USART_MODE_ONLY_RX
 */
#define USART_MODE	USART_MODE_TXRX
/*
 Possible options for USART_HWFlowControl:
 1-USART_HW_FLOW_CTRL_NONE		2-USART_HW_FLOW_CTRL_CTS
 3-USART_HW_FLOW_CTRL_RTS		4-USART_HW_FLOW_CTRL_CTS_RTS
 */
#define USART_HW_FLOW 	USART_HW_FLOW_CTRL_NONE

/*
 Possible options for USART_NoOfStopBits:
 1-USART_STOPBITS_1				2-USART_STOPBITS_0_5
 3-USART_STOPBITS_2				4-USART_STOPBITS_1_5
 */
#define USART_STOPBITS	USART_STOPBITS_1

/*
 Possible options for USART_WordLength:
 1-USART_WORDLEN_8BITS			2-USART_WORDLEN_9BITS
 */
#define USART_WORDLEN	USART_WORDLEN_8BITS

/*
Possible options for USART_ParityControl:
1-USART_PARITY_EN_ODD		2-USART_PARITY_EN_EVEN			3-USART_PARITY_DISABLE
 */
#define USART_PARITYCTRL	USART_PARITY_DISABLE
















#endif
